<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net20</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputPath>./Build/</OutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include=".\Resources\Images\MenuBackground.jpg" />
    <EmbeddedResource Include=".\Resources\Music\Nocturne.wav" />
    <EmbeddedResource Include=".\Resources\Images\Title.png" />
  </ItemGroup>
    
</Project>